DNA= "CCCAGAATGAGTGTAGTCGTGCTTCGGAGGTCAAATCGCTATTTTTACCTCGCTGGCATGATGCTGATTTCAGTGCACGGGTCGTGTGCGGGAGGCTTTGCCTATGACACACGGTCGTGGATGTATTATACTGCTTAGGCGAAACATTCAAGGTGACCCCATTAATAGGAGTGTTTCATCATGGGATATACGATGGGCACAACTCTCCTCCCCCTAGCAGAGCGCGGGTACCTGCCATTTAGCTAGTGTCGGGGGTACCATCTGTACGGTCCGCGCGACCTTGCATAACGCGTGGCGACATCTCTTGCGGAAAGTAATTACCAGTGTTGTAACTAACGCCCGATGCGCAGAACGGAGCTTCGCTTATCCCGATCAAGTCGTTCTTCCCTTGAGCGCATTGCCACAAACGATTGAGCCCTAATTCCGATCATCCTTAAGGAAAGCAGAGGAAACGCCACCTTGATTCGCCAGTGTGTGCGGCCAACATGTGCGCCCTAGGGAGCACCACGCTTTCAAGTCATAAATTGTGGGTCCGCAGTCCCCCATCTTAAAGGCCCAGAACGGTCGTGCAGATGACGGGGAGGAAGAACCGTCTGTCAAAGCGATGAACCAGAGTAACTGTGCCCGTAGACGCCTACGACGAGTCTTTGGGCTCCCACAGCACTGCAAGAAACTCCGGCGGCAGGCATTGTGCGAGACTGGAAGTAGCGGGACATATGCGTATTGCCAGATGCAAACGCAATCCCATGGGACCGTTTACGCCAGAAGACGCGATAACTGTCTACAGCATGTAGCGGAAGTGTTCTGTGTTCTGACGTGGTAAGTCTTAATTCAGCTAAGTTGACTTT"
count_A = 0
count_G = 0
count_T = 0
count_C = 0
count_N = 0
for pair in DNA:
    if pair == 'A':
        count_A += 1
    elif pair == 'G':
        count_G += 1
    elif pair == 'T':
        count_T += 1
    elif pair == 'C':
        count_C += 1
    else:
        count_N += 1

print(count_A ,count_C ,count_G ,count_T)

DNA_dict = {}

for pair in DNA:
    DNA_dict[pair] = DNA_dict.get(pair , 0) + 1 # 由键寻值，若不存在，'0' 为默认值
print(DNA_dict)


